### PR TITLE
new raidmons.json

### PR DESCRIPTION
**Pull request by AboveColin**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] Where appropriate examples are updated such as config.ini.example
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by cookieisland** [comment]
be careful I tried putting 487 in raidmons.json but due to 487/Giratina not yet being in PogoAssets all hell broke loose.  startWalker would no longer run at all.  I ended up putting 487 in config.ini for auto hatch but left 150 in raidmons.json and it (sortof) works......  per this tweet Giratina is missing --> https://twitter.com/Chrales/status/1052073948224135168

**Comment by AboveColin** [comment]
Can you try changing 487 to ```"487_11"```, with the quotation marks? And see if that works?

**Comment by cecpk** [comment]
No - the file dont exists in Assets - thats a problem atm. We could hope, Chrales add it soon!

**Comment by cecpk** [comment]
yes - add "487_11" :)
thx @AboveColin

**Comment by cookieisland** [comment]
"487_11" seems to work.  I also added duskull, shuppet, gengar, etc... the new ones out now....

**Comment by AboveColin** [comment]
I'll add the other bosses in half an hour 😁

**Comment by AboveColin** [comment]
now really ```Ready``` for merge 👍 haha

**Pull request merged**
